name: Nx Affected Test Release
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
env:
    BEFORE_SHA: ${{ github.event.before }}
jobs:
    build:
        name: Build wiki.dailysh.it
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - run: git fetch origin main
            - run: git config --local user.email "action@github.com"
            - run: git config --local user.name "Github Action"
            - name: npm install
              run: npm install
            - name: Run Affected Test-Release
              shell: bash
              run: npm run affected:test -- --base=$BEFORE_SHA
            - name: Build Wiki Bell UI
			  if: ${{ success() }}
              shell: bash
              run: npm run build:wikibell
            - name: Deploy Wiki Bell UI
			  if: ${{ success() }}
              shell: bash
              run: npm run deploy:wikibell
